### ISSUE TITLE
TypeError: Report is not a function (0.4.5)

### ISSUE THREAD

**Issue by girokon** [leinonen/cucumber-html-report#56]
I got this error after update to 0.4.5, my code:

```
'use strict';

const Report = require('cucumber-html-report');

let options = {
    source: 'tests/out/output.json', // source json
    dest: 'tests/out/reports', // target directory (will create if not exists)
    name: 'report.html' // report file name (will be index.html if not exists)
};

let report = new Report(options);
report.createReport();

```

As I see https://github.com/leinonen/cucumber-html-report/blob/master/index.js the index file doesn't export anything

**Comment by leinonen** [comment]
I fucked up. Will fix it asap. I am sorry about that

Den tis 24 jan. 2017 07:18Igor Noskov <notifications@github.com> skrev:

**Comment by tgregoire** [comment]
Thank you, I have the same problem as girokon. I saw that the "how to" section changed in the read me file, is that normal ?

**Comment by leinonen** [comment]
I merged some stuff, that was not working as I wanted it to. And I
accidentally published it..
I am currently rewriting some stuff, that I am not happy with, so there
will be a new fixed version out pretty soon. Stay tuned.
The API will change, but not much.

**Comment by H34D** [comment]
ok thanks for the info i will just stick to the 0.4.4 till this is fixed

**Comment by aluzardo** [comment]
Same problem here. I will downgrade to 0.4.4

**Comment by leinonen** [comment]
There will be a new version out this week.
Sorry for causing problems for you guys :(

**Comment by leinonen** [comment]
There is a new version out now. 0.5.0. Check it out and see how it works for you guys!

**Comment by aluzardo** [comment]
Thanks @leinonen ! I tried to install the new version but it not work for me. I think that my problem is different. I have upgraded from 0.3.5 and maybe something have been changed. I have to see the changelog to try to fix it.

My problem is  `W/launcher - Ignoring uncaught error TypeError: CucumberHtmlReport is not a constructor`

My code is similar than @girokon code.

**Comment by aluzardo** [comment]
Fixed, I updated my code using the https://github.com/leinonen/cucumber-html-report/blob/master/README.md 

I love the new report. Maybe I would suggest use a default logo. My report didn't work at first time because I haven't got any logo, I added a logo and a path and it worked perfectly.

**Comment by leinonen** [comment]
Glad you like it. 
It is supposed to have a default logo if none is provided. I'll look into it and create a new issue for that specific problem.
